% Produced by CVXGEN, 2018-05-11 17:28:57 -0400.
% CVXGEN is Copyright (C) 2006-2017 Jacob Mattingley, jem@cvxgen.com.
% The code in this file is Copyright (C) 2006-2017 Jacob Mattingley.
% CVXGEN, or solvers produced by CVXGEN, cannot be used for commercial
% applications without prior written permission from Jacob Mattingley.

% Filename: cvxsolve.m.
% Description: Solution file, via cvx, for use with sample.m.
function [vars, status] = cvxsolve(params, settings)
A = params.A;
H = params.H;
cvx_begin
  % Caution: automatically generated by cvxgen. May be incorrect.
  variable w(3, 1);

  minimize(quad_form(w, H));
  subject to
    A*w <= -1;
cvx_end
vars.w = w;
status.cvx_status = cvx_status;
% Provide a drop-in replacement for csolve.
status.optval = cvx_optval;
status.converged = strcmp(cvx_status, 'Solved');
